// ═══════════════════════════════════════════════════════════════════════════
// CardPreview module — theme definitions (8 presets)
// ═══════════════════════════════════════════════════════════════════════════

import type { ThemeDefinition } from './types'

export const THEMES: ThemeDefinition[] = [
  // ── 1. moss-paper ──────────────────────────────────────────────────────
  {
    id: 'moss-paper',
    name: '苔绿纸书',
    mood: '浅苔纸面与出版物墨感',
    preset: '浅底苔绿纸书',
    description: '浅苔纸面、安静高级，适合默认长期使用',
    tags: ['复古', '安静'],
    mode: 'paper',
    palette: {
      page: '#f3f1ea',
      pageAlt: '#e6ebdf',
      text: '#1f2b22',
      muted: '#667368',
      accent: '#3f8f58',
      accentSoft: 'rgba(63,143,88,0.18)',
      border: 'rgba(63,77,66,0.12)',
      shadow: 'rgba(63,77,66,0.12)',
      glow: 'rgba(206,215,201,0.34)',
    },
    surface: {
      grainAlpha: 0.038,
      vignetteAlpha: 0.044,
      washStrength: 0.32,
      innerFrameAlpha: 0.11,
      innerFrameInset: 24,
      titleAccentMix: 0.86,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 26px 54px rgba(57,72,60,0.11), 0 2px 18px rgba(255,255,255,0.42) inset',
    },
    components: {
      quoteFillAlpha: 0.042,
      quoteStrokeAlpha: 0.074,
      quoteBarAlpha: 0.72,
      quoteRadius: 22,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.72,
      highlightMarkerAlpha: 0.32,
      highlightDashAlpha: 0.84,
    },
    editor: {
      titleSize: 75,
      bodySize: 30,
      lineHeight: 1.84,
      titleFontMode: 'serif',
      highlightStyle: 'underline',
    },
  },

  // ── 2. warm-editor ─────────────────────────────────────────────────────
  {
    id: 'warm-editor',
    name: '暖灰编辑',
    mood: '清透冷灰与荧光绿效率感',
    preset: '冷灰效率编辑',
    description: '冷灰白底、荧光绿高亮、数字网格，适合智性效率长文',
    tags: ['效率', '数字'],
    mode: 'paper',
    palette: {
      page: '#f8f9fa',
      pageAlt: '#eef2f4',
      text: '#151d20',
      muted: '#5f6b70',
      accent: '#BAF13C',
      accentSoft: 'rgba(186,241,60,0.18)',
      border: 'rgba(19,30,34,0.12)',
      shadow: 'rgba(16,24,28,0.1)',
      glow: 'rgba(186,241,60,0.09)',
    },
    surface: {
      grainAlpha: 0.014,
      vignetteAlpha: 0.018,
      washStrength: 0.16,
      innerFrameAlpha: 0.12,
      innerFrameInset: 24,
      titleAccentMix: 0.7,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 22px 48px rgba(16,24,28,0.09), 0 1px 12px rgba(255,255,255,0.36) inset',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.06,
      quoteBarAlpha: 0.68,
      quoteRadius: 16,
      quoteTreatment: 'callout',
      highlightTreatment: 'editorMark',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.38,
      highlightDashAlpha: 0.78,
    },
    editor: {
      titleSize: 72,
      bodySize: 29,
      lineHeight: 1.82,
      titleFontMode: 'sans',
      highlightStyle: 'marker',
    },
  },

  // ── 3. peach-cloud ─────────────────────────────────────────────────────
  {
    id: 'peach-cloud',
    name: '暖桃云',
    mood: '暖桃粉底复古胶片感',
    preset: '暖桃胶片',
    description: '暖调粉底、柔光氛围，适合生活随笔与心情记录',
    tags: ['温暖', '胶片'],
    mode: 'vintage',
    palette: {
      page: '#fdf5f0',
      pageAlt: '#fce8db',
      text: '#3d2a1d',
      muted: '#8b6f5e',
      accent: '#d4785c',
      accentSoft: 'rgba(212,120,92,0.2)',
      border: 'rgba(120,85,65,0.14)',
      shadow: 'rgba(120,85,65,0.1)',
      glow: 'rgba(255,210,180,0.38)',
    },
    surface: {
      grainAlpha: 0.044,
      vignetteAlpha: 0.052,
      washStrength: 0.38,
      innerFrameAlpha: 0.09,
      innerFrameInset: 26,
      titleAccentMix: 0.82,
      footerLineAlpha: 0.18,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 24px 50px rgba(120,85,65,0.1), 0 2px 16px rgba(255,245,235,0.44) inset',
    },
    components: {
      quoteFillAlpha: 0.05,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.7,
      quoteRadius: 20,
      quoteTreatment: 'paper',
      highlightTreatment: 'warmSwipe',
      highlightUnderlineAlpha: 0.64,
      highlightMarkerAlpha: 0.36,
      highlightDashAlpha: 0.8,
    },
    editor: {
      titleSize: 76,
      bodySize: 30,
      lineHeight: 1.86,
      titleFontMode: 'serif',
      highlightStyle: 'marker',
    },
  },

  // ── 4. lemon-note ──────────────────────────────────────────────────────
  {
    id: 'lemon-note',
    name: '柠黄便签',
    mood: '柠檬黄便签纸质感',
    preset: '柠黄便签',
    description: '明亮柠黄、轻快活泼，适合灵感速记与清单',
    tags: ['明亮', '便签'],
    mode: 'vintage',
    palette: {
      page: '#fffbec',
      pageAlt: '#fef5d0',
      text: '#2d2816',
      muted: '#7a7250',
      accent: '#d4a017',
      accentSoft: 'rgba(212,160,23,0.2)',
      border: 'rgba(160,140,60,0.14)',
      shadow: 'rgba(160,140,60,0.1)',
      glow: 'rgba(255,240,180,0.42)',
    },
    surface: {
      grainAlpha: 0.04,
      vignetteAlpha: 0.048,
      washStrength: 0.34,
      innerFrameAlpha: 0.1,
      innerFrameInset: 24,
      titleAccentMix: 0.78,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 22px 46px rgba(160,140,60,0.1), 0 2px 14px rgba(255,250,220,0.4) inset',
    },
    components: {
      quoteFillAlpha: 0.048,
      quoteStrokeAlpha: 0.076,
      quoteBarAlpha: 0.72,
      quoteRadius: 18,
      quoteTreatment: 'paper',
      highlightTreatment: 'botanicalStroke',
      highlightUnderlineAlpha: 0.68,
      highlightMarkerAlpha: 0.34,
      highlightDashAlpha: 0.82,
    },
    editor: {
      titleSize: 74,
      bodySize: 29,
      lineHeight: 1.84,
      titleFontMode: 'kai',
      highlightStyle: 'underline',
    },
  },

  // ── 5. sage-dawn ───────────────────────────────────────────────────────
  {
    id: 'sage-dawn',
    name: '鼠尾草晨',
    mood: '鼠尾草绿安静治愈',
    preset: '鼠尾草治愈',
    description: '低饱和绿调、安静治愈，适合读书笔记与深度思考',
    tags: ['治愈', '安静'],
    mode: 'sage',
    palette: {
      page: '#f4f6f3',
      pageAlt: '#e8efe5',
      text: '#1e2a1c',
      muted: '#5f6e5c',
      accent: '#6b9b5c',
      accentSoft: 'rgba(107,155,92,0.18)',
      border: 'rgba(80,100,76,0.12)',
      shadow: 'rgba(80,100,76,0.1)',
      glow: 'rgba(210,230,200,0.36)',
    },
    surface: {
      grainAlpha: 0.036,
      vignetteAlpha: 0.042,
      washStrength: 0.3,
      innerFrameAlpha: 0.1,
      innerFrameInset: 24,
      titleAccentMix: 0.84,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 24px 50px rgba(80,100,76,0.1), 0 2px 16px rgba(255,255,255,0.4) inset',
    },
    components: {
      quoteFillAlpha: 0.044,
      quoteStrokeAlpha: 0.072,
      quoteBarAlpha: 0.7,
      quoteRadius: 20,
      quoteTreatment: 'paper',
      highlightTreatment: 'botanicalStroke',
      highlightUnderlineAlpha: 0.7,
      highlightMarkerAlpha: 0.3,
      highlightDashAlpha: 0.82,
    },
    editor: {
      titleSize: 74,
      bodySize: 29,
      lineHeight: 1.84,
      titleFontMode: 'serif',
      highlightStyle: 'underline',
    },
  },

  // ── 6. swiss-modern ────────────────────────────────────────────────────
  {
    id: 'swiss-modern',
    name: '瑞士现代',
    mood: '瑞士极简网格排版',
    preset: '瑞士网格',
    description: '红点 accent、网格秩序，适合设计感与品牌内容',
    tags: ['极简', '设计'],
    mode: 'swiss',
    palette: {
      page: '#fafafa',
      pageAlt: '#fafafa',
      text: '#1a1a1a',
      muted: '#6e6e6e',
      accent: '#d94136',
      accentSoft: 'rgba(217,65,54,0.14)',
      border: 'rgba(30,30,30,0.14)',
      shadow: 'rgba(30,30,30,0.1)',
      glow: 'rgba(217,65,54,0.06)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0.02,
      washStrength: 0,
      innerFrameAlpha: 0.14,
      innerFrameInset: 20,
      titleAccentMix: 0.6,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 18px 40px rgba(30,30,30,0.08), 0 1px 8px rgba(0,0,0,0.04) inset',
    },
    components: {
      quoteFillAlpha: 0.02,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.84,
      quoteRadius: 2,
      quoteTreatment: 'callout',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.26,
      highlightDashAlpha: 0.88,
    },
    editor: {
      titleSize: 78,
      bodySize: 28,
      lineHeight: 1.76,
      titleFontMode: 'sans',
      highlightStyle: 'border',
    },
  },

  // ── 7. forest-archive ──────────────────────────────────────────────────
  {
    id: 'forest-archive',
    name: '森林档案',
    mood: '深绿档案暗底金文',
    preset: '墨绿档案',
    description: '深绿暗底、金字文本，适合仪式感与收藏级内容',
    tags: ['暗色', '档案'],
    mode: 'archive',
    palette: {
      page: '#14281a',
      pageAlt: '#1a3324',
      text: '#d8c99b',
      muted: '#8a9e7e',
      accent: '#c9a84c',
      accentSoft: 'rgba(201,168,76,0.16)',
      border: 'rgba(216,201,155,0.12)',
      shadow: 'rgba(10,20,12,0.3)',
      glow: 'rgba(201,168,76,0.08)',
    },
    surface: {
      grainAlpha: 0.06,
      vignetteAlpha: 0.072,
      washStrength: 0.28,
      innerFrameAlpha: 0.16,
      innerFrameInset: 28,
      titleAccentMix: 0.9,
      footerLineAlpha: 0.24,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 30px 60px rgba(10,20,12,0.36), 0 2px 20px rgba(0,0,0,0.2) inset',
    },
    components: {
      quoteFillAlpha: 0.06,
      quoteStrokeAlpha: 0.1,
      quoteBarAlpha: 0.78,
      quoteRadius: 24,
      quoteTreatment: 'paper',
      highlightTreatment: 'darkGlow',
      highlightUnderlineAlpha: 0.62,
      highlightMarkerAlpha: 0.4,
      highlightDashAlpha: 0.78,
    },
    editor: {
      titleSize: 76,
      bodySize: 30,
      lineHeight: 1.86,
      titleFontMode: 'retroSerif',
      highlightStyle: 'marker',
    },
  },

  // ── 8. deep-obsidian ───────────────────────────────────────────────────
  {
    id: 'deep-obsidian',
    name: '深黑曜石',
    mood: '深黑金戏剧感',
    preset: '黑金曜石',
    description: '极致黑底、金文点睛，适合金句卡片与品牌宣言',
    tags: ['暗色', '戏剧'],
    mode: 'obsidian',
    palette: {
      page: '#151310',
      pageAlt: '#1c1915',
      text: '#e8dcc8',
      muted: '#8a8070',
      accent: '#d4a84b',
      accentSoft: 'rgba(212,168,75,0.16)',
      border: 'rgba(232,220,200,0.1)',
      shadow: 'rgba(8,6,4,0.4)',
      glow: 'rgba(212,168,75,0.1)',
    },
    surface: {
      grainAlpha: 0.08,
      vignetteAlpha: 0.08,
      washStrength: 0.24,
      innerFrameAlpha: 0.18,
      innerFrameInset: 28,
      titleAccentMix: 0.92,
      footerLineAlpha: 0.26,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 32px 64px rgba(8,6,4,0.44), 0 2px 22px rgba(0,0,0,0.24) inset',
    },
    components: {
      quoteFillAlpha: 0.07,
      quoteStrokeAlpha: 0.12,
      quoteBarAlpha: 0.8,
      quoteRadius: 24,
      quoteTreatment: 'paper',
      highlightTreatment: 'darkGlow',
      highlightUnderlineAlpha: 0.6,
      highlightMarkerAlpha: 0.42,
      highlightDashAlpha: 0.76,
    },
    editor: {
      titleSize: 78,
      bodySize: 30,
      lineHeight: 1.88,
      titleFontMode: 'retroSerif',
      highlightStyle: 'marker',
    },
  },
]

/** Default theme ID used when none is specified. */
export const DEFAULT_THEME_ID = 'moss-paper'

/** Look up a theme by ID. Falls back to the first theme. */
export function getTheme(id: string): ThemeDefinition {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}
