// ═══════════════════════════════════════════════════════════════════════════
// CardPreview 模块 — 主题定义（8 个预设）
// ═══════════════════════════════════════════════════════════════════════════

import type { ThemeDefinition } from './types'

export const THEMES: ThemeDefinition[] = [
  // ── 1. moss-paper ──────────────────────────────────────────────────────
  {
    id: 'moss-paper',
    name: '苔绿纸书',
    mood: '浅苔纸面与出版物墨感',
    preset: '浅底苔绿纸书',
    description: '浅苔纸面、安静高级，适合默认长期使用',
    tags: ['复古', '安静'],
    mode: 'paper',
    palette: {
      page: '#f3f1ea',
      pageAlt: '#e6ebdf',
      text: '#1f2b22',
      muted: '#667368',
      accent: '#3f8f58',
      accentSoft: 'rgba(63,143,88,0.18)',
      border: 'rgba(63,77,66,0.12)',
      shadow: 'rgba(63,77,66,0.12)',
      glow: 'rgba(206,215,201,0.34)',
    },
    surface: {
      grainAlpha: 0.038,
      vignetteAlpha: 0.044,
      washStrength: 0.32,
      innerFrameAlpha: 0.11,
      innerFrameInset: 24,
      titleAccentMix: 0.86,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 26px 54px rgba(57,72,60,0.11), 0 2px 18px rgba(255,255,255,0.42) inset',
    },
    components: {
      quoteFillAlpha: 0.042,
      quoteStrokeAlpha: 0.074,
      quoteBarAlpha: 0.72,
      quoteRadius: 22,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.72,
      highlightMarkerAlpha: 0.32,
      highlightDashAlpha: 0.84,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.84,
      bodyFontMode: 'wenkai',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#e6ebdf', color2: '#f3f1ea' },
  },

  // ── 2. warm-editor ─────────────────────────────────────────────────────
  {
    id: 'warm-editor',
    name: '暖灰编辑',
    mood: '清透冷灰与荧光绿效率感',
    preset: '冷灰效率编辑',
    description: '冷灰白底、荧光绿高亮、数字网格，适合智性效率长文',
    tags: ['效率', '数字'],
    mode: 'paper',
    palette: {
      page: '#f8f9fa',
      pageAlt: '#eef2f4',
      text: '#151d20',
      muted: '#5f6b70',
      accent: '#BAF13C',
      accentSoft: 'rgba(186,241,60,0.18)',
      border: 'rgba(19,30,34,0.12)',
      shadow: 'rgba(16,24,28,0.1)',
      glow: 'rgba(186,241,60,0.09)',
    },
    surface: {
      grainAlpha: 0.014,
      vignetteAlpha: 0.018,
      washStrength: 0.16,
      innerFrameAlpha: 0.12,
      innerFrameInset: 24,
      titleAccentMix: 0.7,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 22px 48px rgba(16,24,28,0.09), 0 1px 12px rgba(255,255,255,0.36) inset',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.06,
      quoteBarAlpha: 0.68,
      quoteRadius: 16,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.38,
      highlightDashAlpha: 0.78,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.82,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'professional',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#eef2f4', color2: '#f8f9fa' },
  },

  // ── 3. peach-cloud ─────────────────────────────────────────────────────
  {
    id: 'peach-cloud',
    name: '暖桃云',
    mood: '暖桃粉底复古胶片感',
    preset: '暖桃胶片',
    description: '暖调粉底、柔光氛围，适合生活随笔与心情记录',
    tags: ['温暖', '胶片'],
    mode: 'vintage',
    palette: {
      page: '#fdf5f0',
      pageAlt: '#fce8db',
      text: '#3d2a1d',
      muted: '#8b6f5e',
      accent: '#d4785c',
      accentSoft: 'rgba(212,120,92,0.2)',
      border: 'rgba(120,85,65,0.14)',
      shadow: 'rgba(120,85,65,0.1)',
      glow: 'rgba(255,210,180,0.38)',
    },
    surface: {
      grainAlpha: 0.044,
      vignetteAlpha: 0.052,
      washStrength: 0.38,
      innerFrameAlpha: 0.09,
      innerFrameInset: 26,
      titleAccentMix: 0.82,
      footerLineAlpha: 0.18,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 24px 50px rgba(120,85,65,0.1), 0 2px 16px rgba(255,245,235,0.44) inset',
    },
    components: {
      quoteFillAlpha: 0.05,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.7,
      quoteRadius: 20,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.64,
      highlightMarkerAlpha: 0.36,
      highlightDashAlpha: 0.8,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.86,
      bodyFontMode: 'wenkai',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#fce8db', color2: '#fdf5f0' },
  },

  // ── 4. lemon-note ──────────────────────────────────────────────────────
  {
    id: 'lemon-note',
    name: '柠黄便签',
    mood: '柠檬黄便签纸质感',
    preset: '柠黄便签',
    description: '明亮柠黄、轻快活泼，适合灵感速记与清单',
    tags: ['明亮', '便签'],
    mode: 'vintage',
    palette: {
      page: '#fffbec',
      pageAlt: '#fef5d0',
      text: '#2d2816',
      muted: '#7a7250',
      accent: '#d4a017',
      accentSoft: 'rgba(212,160,23,0.2)',
      border: 'rgba(160,140,60,0.14)',
      shadow: 'rgba(160,140,60,0.1)',
      glow: 'rgba(255,240,180,0.42)',
    },
    surface: {
      grainAlpha: 0.04,
      vignetteAlpha: 0.048,
      washStrength: 0.34,
      innerFrameAlpha: 0.1,
      innerFrameInset: 24,
      titleAccentMix: 0.78,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 22px 46px rgba(160,140,60,0.1), 0 2px 14px rgba(255,250,220,0.4) inset',
    },
    components: {
      quoteFillAlpha: 0.048,
      quoteStrokeAlpha: 0.076,
      quoteBarAlpha: 0.72,
      quoteRadius: 18,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.68,
      highlightMarkerAlpha: 0.34,
      highlightDashAlpha: 0.82,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.84,
      bodyFontMode: 'kaiti',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#fef5d0', color2: '#fffbec' },
  },

  // ── 5. sage-dawn ───────────────────────────────────────────────────────
  {
    id: 'sage-dawn',
    name: '鼠尾草晨',
    mood: '鼠尾草绿安静治愈',
    preset: '鼠尾草治愈',
    description: '低饱和绿调、安静治愈，适合读书笔记与深度思考',
    tags: ['治愈', '安静'],
    mode: 'sage',
    palette: {
      page: '#f4f6f3',
      pageAlt: '#e8efe5',
      text: '#1e2a1c',
      muted: '#5f6e5c',
      accent: '#6b9b5c',
      accentSoft: 'rgba(107,155,92,0.18)',
      border: 'rgba(80,100,76,0.12)',
      shadow: 'rgba(80,100,76,0.1)',
      glow: 'rgba(210,230,200,0.36)',
    },
    surface: {
      grainAlpha: 0.036,
      vignetteAlpha: 0.042,
      washStrength: 0.3,
      innerFrameAlpha: 0.1,
      innerFrameInset: 24,
      titleAccentMix: 0.84,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 24px 50px rgba(80,100,76,0.1), 0 2px 16px rgba(255,255,255,0.4) inset',
    },
    components: {
      quoteFillAlpha: 0.044,
      quoteStrokeAlpha: 0.072,
      quoteBarAlpha: 0.7,
      quoteRadius: 20,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.7,
      highlightMarkerAlpha: 0.3,
      highlightDashAlpha: 0.82,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.84,
      bodyFontMode: 'wenkai',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#e8efe5', color2: '#f4f6f3' },
  },

  // ── 6. swiss-modern ────────────────────────────────────────────────────
  {
    id: 'swiss-modern',
    name: '瑞士现代',
    mood: '瑞士极简网格排版',
    preset: '瑞士网格',
    description: '红点 accent、网格秩序，适合设计感与品牌内容',
    tags: ['极简', '设计'],
    mode: 'swiss',
    palette: {
      page: '#fafafa',
      pageAlt: '#fafafa',
      text: '#1a1a1a',
      muted: '#6e6e6e',
      accent: '#d94136',
      accentSoft: 'rgba(217,65,54,0.14)',
      border: 'rgba(30,30,30,0.14)',
      shadow: 'rgba(30,30,30,0.1)',
      glow: 'rgba(217,65,54,0.06)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0.02,
      washStrength: 0,
      innerFrameAlpha: 0.14,
      innerFrameInset: 20,
      titleAccentMix: 0.6,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 18px 40px rgba(30,30,30,0.08), 0 1px 8px rgba(0,0,0,0.04) inset',
    },
    components: {
      quoteFillAlpha: 0.02,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.84,
      quoteRadius: 2,
      quoteTreatment: 'callout',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.26,
      highlightDashAlpha: 0.88,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.76,
      bodyFontMode: 'yahei',
      bodyFontWeight: 350,
      subheadingStyle: 'large',
      highlightStyle: 'border',
    },
    category: 'professional',
    decor: { kind: 'cornerBracket', opacity: 0.3, scale: 1 },
    gradient: { enabled: true, color1: '#fafafa', color2: '#d94136' },
  },

  // ── 7. forest-archive ──────────────────────────────────────────────────
  {
    id: 'forest-archive',
    name: '森林档案',
    mood: '深绿档案暗底金文',
    preset: '墨绿档案',
    description: '深绿暗底、金字文本，适合仪式感与收藏级内容',
    tags: ['暗色', '档案'],
    mode: 'archive',
    palette: {
      page: '#14281a',
      pageAlt: '#1a3324',
      text: '#d8c99b',
      muted: '#8a9e7e',
      accent: '#c9a84c',
      accentSoft: 'rgba(201,168,76,0.16)',
      border: 'rgba(216,201,155,0.12)',
      shadow: 'rgba(10,20,12,0.3)',
      glow: 'rgba(201,168,76,0.08)',
    },
    surface: {
      grainAlpha: 0.06,
      vignetteAlpha: 0.072,
      washStrength: 0.28,
      innerFrameAlpha: 0.16,
      innerFrameInset: 28,
      titleAccentMix: 0.9,
      footerLineAlpha: 0.24,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 30px 60px rgba(10,20,12,0.36), 0 2px 20px rgba(0,0,0,0.2) inset',
    },
    components: {
      quoteFillAlpha: 0.06,
      quoteStrokeAlpha: 0.1,
      quoteBarAlpha: 0.78,
      quoteRadius: 24,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.62,
      highlightMarkerAlpha: 0.4,
      highlightDashAlpha: 0.78,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.86,
      bodyFontMode: 'simsun',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'topRule', opacity: 0.24, scale: 1 },
    gradient: { enabled: true, color1: '#14281a', color2: '#c9a84c' },
  },

  // ── 8. deep-obsidian ───────────────────────────────────────────────────
  {
    id: 'deep-obsidian',
    name: '深黑曜石',
    mood: '深黑金戏剧感',
    preset: '黑金曜石',
    description: '极致黑底、金文点睛，适合金句卡片与品牌宣言',
    tags: ['暗色', '戏剧'],
    mode: 'obsidian',
    palette: {
      page: '#151310',
      pageAlt: '#1c1915',
      text: '#e8dcc8',
      muted: '#8a8070',
      accent: '#d4a84b',
      accentSoft: 'rgba(212,168,75,0.16)',
      border: 'rgba(232,220,200,0.1)',
      shadow: 'rgba(8,6,4,0.4)',
      glow: 'rgba(212,168,75,0.1)',
    },
    surface: {
      grainAlpha: 0.08,
      vignetteAlpha: 0.08,
      washStrength: 0.24,
      innerFrameAlpha: 0.18,
      innerFrameInset: 28,
      titleAccentMix: 0.92,
      footerLineAlpha: 0.26,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 32px 64px rgba(8,6,4,0.44), 0 2px 22px rgba(0,0,0,0.24) inset',
    },
    components: {
      quoteFillAlpha: 0.07,
      quoteStrokeAlpha: 0.12,
      quoteBarAlpha: 0.8,
      quoteRadius: 24,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.6,
      highlightMarkerAlpha: 0.42,
      highlightDashAlpha: 0.76,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.88,
      bodyFontMode: 'simsun',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'topRule', opacity: 0.28, scale: 1 },
    gradient: { enabled: true, color1: '#151310', color2: '#d4a84b' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── 9. ink-wash (水墨丹青) ──────────────────────────────────────────────
  {
    id: 'ink-wash',
    name: '水墨丹青',
    mood: '黑白水墨画意留白',
    preset: '水墨留白',
    description: '宣纸墨色、大量留白、书法韵味，适合古风诗词与哲思散文',
    tags: ['水墨', '留白', '古风'],
    mode: 'paper',
    palette: {
      page: '#f7f5f0',
      pageAlt: '#ede8df',
      text: '#1a1a1a',
      muted: '#8c8c8c',
      accent: '#2c2c2c',
      accentSoft: 'rgba(44,44,44,0.08)',
      border: 'rgba(44,44,44,0.08)',
      shadow: 'rgba(0,0,0,0.06)',
      glow: 'rgba(200,195,185,0.18)',
    },
    surface: {
      grainAlpha: 0.028,
      vignetteAlpha: 0.032,
      washStrength: 0.12,
      innerFrameAlpha: 0.06,
      innerFrameInset: 32,
      titleAccentMix: 0.45,
      footerLineAlpha: 0.14,
      footerTextAlpha: 0.82,
      previewShadow:
        '0 20px 44px rgba(0,0,0,0.06), 0 1px 10px rgba(255,255,255,0.3) inset',
    },
    components: {
      quoteFillAlpha: 0.02,
      quoteStrokeAlpha: 0.04,
      quoteBarAlpha: 0.55,
      quoteRadius: 2,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.35,
      highlightMarkerAlpha: 0.15,
      highlightDashAlpha: 0.4,
    },
    editor: {
      bodySize: 30,
      lineHeight: 2.0,
      bodyFontMode: 'kaiti',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'watermark', opacity: 0.06, scale: 1.2 },
    gradient: { enabled: false, color1: '#ede8df', color2: '#f7f5f0' },
  },

  // ── 10. cyber-neon (赛博霓虹) ──────────────────────────────────────────
  {
    id: 'cyber-neon',
    name: '赛博霓虹',
    mood: '暗紫黑底赛博朋克霓虹',
    preset: '霓虹代码',
    description: '暗紫黑底、青霓虹高亮、终端扫描线，适合科技文章与代码卡片',
    tags: ['赛博', '霓虹', '科技'],
    mode: 'cyber',
    palette: {
      page: '#0a0a12',
      pageAlt: '#0f0c1a',
      text: '#c8d6e5',
      muted: '#6b7d95',
      accent: '#00f0ff',
      accentSoft: 'rgba(0,240,255,0.14)',
      border: 'rgba(0,240,255,0.15)',
      shadow: 'rgba(0,240,255,0.12)',
      glow: 'rgba(0,240,255,0.08)',
    },
    surface: {
      grainAlpha: 0.02,
      vignetteAlpha: 0.06,
      washStrength: 0.2,
      innerFrameAlpha: 0.14,
      innerFrameInset: 18,
      titleAccentMix: 0.88,
      footerLineAlpha: 0.22,
      footerTextAlpha: 0.84,
      previewShadow:
        '0 0 40px rgba(0,240,255,0.1), 0 0 80px rgba(180,0,255,0.06), 0 2px 16px rgba(0,0,0,0.4) inset',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.1,
      quoteBarAlpha: 0.78,
      quoteRadius: 4,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.56,
      highlightMarkerAlpha: 0.36,
      highlightDashAlpha: 0.74,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.78,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'circuitTrace', opacity: 0.12, color: '#00f0ff', scale: 1 },
    gradient: { enabled: true, color1: '#00f0ff', color2: '#b400ff' },
  },

  // ── 11. glass-morph (冰霜玻璃) ─────────────────────────────────────────
  {
    id: 'glass-morph',
    name: '冰霜玻璃',
    mood: '毛玻璃质感虹彩渐变',
    preset: '玻璃虹彩',
    description: '半透明毛玻璃层叠、柔光虹彩渐变，适合创意设计与品牌内容',
    tags: ['玻璃', '虹彩', '现代'],
    mode: 'glass',
    palette: {
      page: 'rgba(255,255,255,0.55)',
      pageAlt: 'rgba(245,240,255,0.45)',
      text: '#1a1530',
      muted: '#6e6888',
      accent: '#6c5ce7',
      accentSoft: 'rgba(108,92,231,0.16)',
      border: 'rgba(108,92,231,0.14)',
      shadow: 'rgba(108,92,231,0.1)',
      glow: 'rgba(180,160,255,0.14)',
    },
    surface: {
      grainAlpha: 0.006,
      vignetteAlpha: 0.02,
      washStrength: 0.22,
      innerFrameAlpha: 0.08,
      innerFrameInset: 20,
      titleAccentMix: 0.72,
      footerLineAlpha: 0.16,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 16px 40px rgba(108,92,231,0.12), 0 2px 12px rgba(255,255,255,0.5) inset, 0 0 0 1px rgba(255,255,255,0.3) inset',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.66,
      quoteRadius: 12,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.6,
      highlightMarkerAlpha: 0.28,
      highlightDashAlpha: 0.7,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.8,
      bodyFontMode: 'yahei',
      bodyFontWeight: 350,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: true, color1: '#6c5ce7', color2: '#a29bfe' },
  },

  // ── 12. brutalist-raw (粗野主义) ───────────────────────────────────────
  {
    id: 'brutalist-raw',
    name: '粗野主义',
    mood: '极致黑白粗边框反设计',
    preset: '粗野黑白',
    description: '高对比黑白、粗边框、等宽标题，反精致审美的原始力量感',
    tags: ['粗野', '黑白', '反设计'],
    mode: 'brutal',
    palette: {
      page: '#ffffff',
      pageAlt: '#ffffff',
      text: '#000000',
      muted: '#444444',
      accent: '#000000',
      accentSoft: 'rgba(0,0,0,0.08)',
      border: 'rgba(0,0,0,0.9)',
      shadow: 'rgba(0,0,0,0)',
      glow: 'rgba(0,0,0,0)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0,
      washStrength: 0,
      innerFrameAlpha: 0.9,
      innerFrameInset: 12,
      titleAccentMix: 0,
      footerLineAlpha: 0.9,
      footerTextAlpha: 1,
      previewShadow:
        '4px 4px 0px rgba(0,0,0,0.9)',
    },
    components: {
      quoteFillAlpha: 0,
      quoteStrokeAlpha: 0.9,
      quoteBarAlpha: 1,
      quoteRadius: 0,
      quoteTreatment: 'code',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.9,
      highlightMarkerAlpha: 0.7,
      highlightDashAlpha: 1,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.65,
      bodyFontMode: 'dengxian',
      bodyFontWeight: 500,
      subheadingStyle: 'large',
      highlightStyle: 'border',
    },
    category: 'professional',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#ffffff', color2: '#ffffff' },
  },

  // ── 13. gold-luxe (鎏金奢) ─────────────────────────────────────────────
  {
    id: 'gold-luxe',
    name: '鎏金奢',
    mood: '象牙金箔奢华质感',
    preset: '鎏金质感',
    description: '象牙白底、金箔点缀、衬线标题，适合高端品牌与邀请函',
    tags: ['奢华', '金箔', '高端'],
    mode: 'luxe',
    palette: {
      page: '#fdfaf3',
      pageAlt: '#f7f0e0',
      text: '#2d2218',
      muted: '#8a7a65',
      accent: '#c8a44e',
      accentSoft: 'rgba(200,164,78,0.18)',
      border: 'rgba(200,164,78,0.2)',
      shadow: 'rgba(120,100,60,0.08)',
      glow: 'rgba(220,190,110,0.2)',
    },
    surface: {
      grainAlpha: 0.022,
      vignetteAlpha: 0.034,
      washStrength: 0.2,
      innerFrameAlpha: 0.1,
      innerFrameInset: 28,
      titleAccentMix: 0.92,
      footerLineAlpha: 0.18,
      footerTextAlpha: 0.9,
      previewShadow:
        '0 24px 56px rgba(120,100,60,0.1), 0 2px 18px rgba(255,250,235,0.5) inset, 0 0 0 1px rgba(200,164,78,0.15) inset',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.8,
      quoteRadius: 16,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.7,
      highlightMarkerAlpha: 0.3,
      highlightDashAlpha: 0.76,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.9,
      bodyFontMode: 'simsun',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'professional',
    decor: { kind: 'goldFoil', opacity: 0.12, color: '#c8a44e', scale: 1 },
    gradient: { enabled: false, color1: '#f7f0e0', color2: '#fdfaf3' },
  },

  // ── 14. botanical-field (原野手札) ─────────────────────────────────────
  {
    id: 'botanical-field',
    name: '原野手札',
    mood: '植物图鉴手绘田野笔记',
    preset: '植物手札',
    description: '暖草纸底、植物绿调、手写标题，适合自然笔记与田野记录',
    tags: ['自然', '手绘', '植物'],
    mode: 'sage',
    palette: {
      page: '#f8f5ed',
      pageAlt: '#efe8d6',
      text: '#2d3320',
      muted: '#7a8065',
      accent: '#5c8a3c',
      accentSoft: 'rgba(92,138,60,0.16)',
      border: 'rgba(92,110,70,0.12)',
      shadow: 'rgba(80,100,60,0.08)',
      glow: 'rgba(180,210,160,0.24)',
    },
    surface: {
      grainAlpha: 0.04,
      vignetteAlpha: 0.04,
      washStrength: 0.26,
      innerFrameAlpha: 0.08,
      innerFrameInset: 26,
      titleAccentMix: 0.8,
      footerLineAlpha: 0.18,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 22px 48px rgba(80,100,60,0.08), 0 2px 14px rgba(255,250,235,0.4) inset',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.07,
      quoteBarAlpha: 0.68,
      quoteRadius: 14,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.64,
      highlightMarkerAlpha: 0.26,
      highlightDashAlpha: 0.72,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.86,
      bodyFontMode: 'kaiti',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'leafMotif', opacity: 0.14, color: '#5c8a3c', scale: 0.9 },
    gradient: { enabled: false, color1: '#efe8d6', color2: '#f8f5ed' },
  },

  // ── 15. arctic-frost (极光冰原) ────────────────────────────────────────
  {
    id: 'arctic-frost',
    name: '极光冰原',
    mood: '冰蓝结晶极光渐变',
    preset: '冰晶极光',
    description: '冰蓝渐变、结晶几何纹理、极光光晕，适合冬日主题与清新内容',
    tags: ['冰蓝', '极光', '清新'],
    mode: 'frost',
    palette: {
      page: '#f4f9fc',
      pageAlt: '#e6f2f9',
      text: '#1a2a38',
      muted: '#5f7d8e',
      accent: '#3a9bc9',
      accentSoft: 'rgba(58,155,201,0.16)',
      border: 'rgba(58,155,201,0.14)',
      shadow: 'rgba(40,100,140,0.08)',
      glow: 'rgba(180,220,245,0.24)',
    },
    surface: {
      grainAlpha: 0.01,
      vignetteAlpha: 0.024,
      washStrength: 0.18,
      innerFrameAlpha: 0.07,
      innerFrameInset: 22,
      titleAccentMix: 0.7,
      footerLineAlpha: 0.16,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 18px 42px rgba(40,100,140,0.08), 0 2px 12px rgba(255,255,255,0.44) inset',
    },
    components: {
      quoteFillAlpha: 0.03,
      quoteStrokeAlpha: 0.06,
      quoteBarAlpha: 0.64,
      quoteRadius: 10,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.24,
      highlightDashAlpha: 0.68,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.8,
      bodyFontMode: 'yahei',
      bodyFontWeight: 350,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'geometricPattern', opacity: 0.08, color: '#3a9bc9', scale: 1 },
    gradient: { enabled: true, color1: '#3a9bc9', color2: '#e6f2f9' },
  },

  // ── 16. midnight-ink (午夜墨蓝) ────────────────────────────────────────
  {
    id: 'midnight-ink',
    name: '午夜墨蓝',
    mood: '深蓝黑底银月星光',
    preset: '墨蓝星空',
    description: '深蓝黑底、银色文字、星点微光，适合深夜写作与深度内容',
    tags: ['午夜', '星空', '深邃'],
    mode: 'obsidian',
    palette: {
      page: '#0d1117',
      pageAlt: '#111820',
      text: '#c8d0da',
      muted: '#6b7888',
      accent: '#7eb8da',
      accentSoft: 'rgba(126,184,218,0.14)',
      border: 'rgba(200,210,220,0.08)',
      shadow: 'rgba(4,8,14,0.5)',
      glow: 'rgba(126,184,218,0.08)',
    },
    surface: {
      grainAlpha: 0.04,
      vignetteAlpha: 0.08,
      washStrength: 0.18,
      innerFrameAlpha: 0.14,
      innerFrameInset: 26,
      titleAccentMix: 0.84,
      footerLineAlpha: 0.2,
      footerTextAlpha: 0.82,
      previewShadow:
        '0 28px 60px rgba(4,8,14,0.5), 0 2px 20px rgba(0,0,0,0.3) inset',
    },
    components: {
      quoteFillAlpha: 0.05,
      quoteStrokeAlpha: 0.1,
      quoteBarAlpha: 0.72,
      quoteRadius: 18,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.54,
      highlightMarkerAlpha: 0.34,
      highlightDashAlpha: 0.66,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.88,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'watermark', opacity: 0.05, color: '#7eb8da', scale: 1.4 },
    gradient: { enabled: true, color1: '#0d1117', color2: '#7eb8da' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── 17。 apple-note (苹果备忘录) ──────────────────────────────────────────
  {
    id: 'apple-note',
    name: '苹果备忘录',
    mood: 'iOS备忘录淡黄纸质感',
    preset: 'iOS便签',
    description: '模拟iOS备忘录淡黄便签纸、温暖干净、苹方标题，适合日常记录与清单',
    tags: ['iOS', '便签', '简约'],
    mode: 'paper',
    palette: {
      page: '#fff9e6',
      pageAlt: '#faf0cf',
      text: '#2d2d2d',
      muted: '#8e8e8e',
      accent: '#f0c840',
      accentSoft: 'rgba(240,200,64,0.18)',
      border: 'rgba(180,170,140,0.14)',
      shadow: 'rgba(160,150,120,0.10)',
      glow: 'rgba(255,245,210,0.30)',
    },
    surface: {
      grainAlpha: 0.024,
      vignetteAlpha: 0.028,
      washStrength: 0.22,
      innerFrameAlpha: 0.08,
      innerFrameInset: 22,
      titleAccentMix: 0.68,
      footerLineAlpha: 0.18,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 20px 44px rgba(160,150,120,0.10), 0 2px 14px rgba(255,250,230,0.40) inset',
    },
    components: {
      quoteFillAlpha: 0.040,
      quoteStrokeAlpha: 0.070,
      quoteBarAlpha: 0.68,
      quoteRadius: 18,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.66,
      highlightMarkerAlpha: 0.28,
      highlightDashAlpha: 0.78,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.80,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#faf0cf', color2: '#fff9e6' },
  },

  // ── 18。 notebook-paper (笔记本) ──────────────────────────────────────────
  {
    id: 'notebook-paper',
    name: '笔记本',
    mood: '横线笔记本蓝墨手写感',
    preset: '学生笔记',
    description: '白色横线纸、蓝色墨水、红边距线、活页孔，适合学习笔记与整理',
    tags: ['笔记', '学习', '手写'],
    mode: 'paper',
    palette: {
      page: '#fdfdfb',
      pageAlt: '#f0f1f5',
      text: '#1a1a2e',
      muted: '#6b7d95',
      accent: '#2563eb',
      accentSoft: 'rgba(37,99,235,0.16)',
      border: 'rgba(37,99,235,0.12)',
      shadow: 'rgba(40,80,140,0.08)',
      glow: 'rgba(220,235,255,0.28)',
    },
    surface: {
      grainAlpha: 0.018,
      vignetteAlpha: 0.022,
      washStrength: 0.14,
      innerFrameAlpha: 0.07,
      innerFrameInset: 20,
      titleAccentMix: 0.65,
      footerLineAlpha: 0.16,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 20px 42px rgba(40,80,140,0.08), 0 1px 12px rgba(255,255,250,0.36) inset',
    },
    components: {
      quoteFillAlpha: 0.036,
      quoteStrokeAlpha: 0.064,
      quoteBarAlpha: 0.64,
      quoteRadius: 10,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.62,
      highlightMarkerAlpha: 0.26,
      highlightDashAlpha: 0.74,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.78,
      bodyFontMode: 'kaiti',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#f0f1f5', color2: '#fdfdfb' },
  },

  // ── 19。 chinese-trad (中国传统) ────────────────────────────────────────
  {
    id: 'chinese-trad',
    name: '中国传统',
    mood: '宣纸水墨朱红印章古韵',
    preset: '水墨古韵',
    description: '宣纸纹理、水墨晕染、朱红印章、古典版式，适合古风诗词与哲思散文',
    tags: ['传统', '水墨', '古典'],
    mode: 'paper',
    palette: {
      page: '#f5ede0',
      pageAlt: '#ebe0ce',
      text: '#1a1a1a',
      muted: '#8c8c8c',
      accent: '#c41e3a',
      accentSoft: 'rgba(196,30,58,0.12)',
      border: 'rgba(160,140,120,0.10)',
      shadow: 'rgba(0,0,0,0.05)',
      glow: 'rgba(220,210,195,0.18)',
    },
    surface: {
      grainAlpha: 0.034,
      vignetteAlpha: 0.032,
      washStrength: 0.16,
      innerFrameAlpha: 0.06,
      innerFrameInset: 32,
      titleAccentMix: 0.50,
      footerLineAlpha: 0.14,
      footerTextAlpha: 0.82,
      previewShadow:
        '0 20px 44px rgba(0,0,0,0.05), 0 1px 10px rgba(255,250,240,0.32) inset',
    },
    components: {
      quoteFillAlpha: 0.024,
      quoteStrokeAlpha: 0.044,
      quoteBarAlpha: 0.52,
      quoteRadius: 2,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.36,
      highlightMarkerAlpha: 0.16,
      highlightDashAlpha: 0.42,
    },
    editor: {
      bodySize: 30,
      lineHeight: 2.0,
      bodyFontMode: 'fangsong',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'watermark', opacity: 0.06, color: '#c41e3a', scale: 1.2 },
    gradient: { enabled: false, color1: '#ebe0ce', color2: '#f5ede0' },
  },

  // ── 20。 alibaba-orange (阿里橙) ────────────────────────────────────────
  {
    id: 'alibaba-orange',
    name: '阿里橙',
    mood: '阿里品牌橙温暖活力',
    preset: '阿里活力橙',
    description: '阿里橙色主调、白底橙条、电商活力，适合互联网内容与品牌卡片',
    tags: ['阿里', '橙色', '电商'],
    mode: 'paper',
    palette: {
      page: '#fefaf5',
      pageAlt: '#faf0e0',
      text: '#1a1a1a',
      muted: '#6e6e6e',
      accent: '#ff6a00',
      accentSoft: 'rgba(255,106,0,0.18)',
      border: 'rgba(255,106,0,0.16)',
      shadow: 'rgba(180,100,40,0.08)',
      glow: 'rgba(255,180,120,0.24)',
    },
    surface: {
      grainAlpha: 0.020,
      vignetteAlpha: 0.024,
      washStrength: 0.20,
      innerFrameAlpha: 0.10,
      innerFrameInset: 22,
      titleAccentMix: 0.74,
      footerLineAlpha: 0.20,
      footerTextAlpha: 0.90,
      previewShadow:
        '0 22px 48px rgba(180,100,40,0.08), 0 2px 14px rgba(255,245,235,0.38) inset',
    },
    components: {
      quoteFillAlpha: 0.040,
      quoteStrokeAlpha: 0.066,
      quoteBarAlpha: 0.74,
      quoteRadius: 12,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.66,
      highlightMarkerAlpha: 0.38,
      highlightDashAlpha: 0.82,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.82,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'professional',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#faf0e0', color2: '#fefaf5' },
  },

  // ── 21。 japanese-mag (日本杂志) ────────────────────────────────────────
  {
    id: 'japanese-mag',
    name: '日本杂志',
    mood: '日系杂志排版错落美学',
    preset: '日杂编辑',
    description: '米白背景、日系排版、留白与密集对比、精致字体层级，适合编辑内容与专栏',
    tags: ['日系', '杂志', '排版'],
    mode: 'paper',
    palette: {
      page: '#faf9f5',
      pageAlt: '#f0ede5',
      text: '#1a1a1a',
      muted: '#6e6e6e',
      accent: '#2d3436',
      accentSoft: 'rgba(45,52,54,0.10)',
      border: 'rgba(45,52,54,0.10)',
      shadow: 'rgba(0,0,0,0.05)',
      glow: 'rgba(200,195,185,0.16)',
    },
    surface: {
      grainAlpha: 0.024,
      vignetteAlpha: 0.028,
      washStrength: 0.16,
      innerFrameAlpha: 0.09,
      innerFrameInset: 24,
      titleAccentMix: 0.56,
      footerLineAlpha: 0.16,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 18px 40px rgba(0,0,0,0.05), 0 1px 10px rgba(255,255,250,0.30) inset',
    },
    components: {
      quoteFillAlpha: 0.026,
      quoteStrokeAlpha: 0.050,
      quoteBarAlpha: 0.56,
      quoteRadius: 2,
      quoteTreatment: 'callout',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.46,
      highlightMarkerAlpha: 0.18,
      highlightDashAlpha: 0.60,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.84,
      bodyFontMode: 'simsun',
      bodyFontWeight: 350,
      subheadingStyle: 'accent',
      highlightStyle: 'border',
    },
    category: 'professional',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#f0ede5', color2: '#faf9f5' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Vintage mode ──────────────────────────────────────────────────────────

  // ── 22。 vintage-typewriter (复古打字机) ────────────────────────────────
  {
    id: 'vintage-typewriter',
    name: '复古打字机',
    mood: '泛黄纸打字机墨迹怀旧',
    preset: '打字机文书',
    description: '泛黄纸纹理、等宽字体、不均匀墨迹、1950年代文书质感，适合怀旧文学与引述',
    tags: ['打字机', '怀旧', '文学'],
    mode: 'vintage',
    palette: {
      page: '#f4efe4',
      pageAlt: '#ece5d5',
      text: '#2d2218',
      muted: '#8a7a6a',
      accent: '#5a4028',
      accentSoft: 'rgba(90,64,40,0.16)',
      border: 'rgba(140,120,90,0.14)',
      shadow: 'rgba(120,100,70,0.12)',
      glow: 'rgba(220,200,170,0.22)',
    },
    surface: {
      grainAlpha: 0.054,
      vignetteAlpha: 0.060,
      washStrength: 0.40,
      innerFrameAlpha: 0.10,
      innerFrameInset: 24,
      titleAccentMix: 0.80,
      footerLineAlpha: 0.20,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 26px 54px rgba(120,100,70,0.12), 0 2px 18px rgba(240,230,210,0.40) inset',
    },
    components: {
      quoteFillAlpha: 0.054,
      quoteStrokeAlpha: 0.086,
      quoteBarAlpha: 0.74,
      quoteRadius: 8,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.62,
      highlightMarkerAlpha: 0.30,
      highlightDashAlpha: 0.76,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.82,
      bodyFontMode: 'simsun',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'watermark', opacity: 0.04, scale: 1.1 },
    gradient: { enabled: false, color1: '#ece5d5', color2: '#f4efe4' },
  },

  // ── 23。 kraft-paper (复古牛皮纸) ──────────────────────────────────────
  {
    id: 'kraft-paper',
    name: '复古牛皮纸',
    mood: '牛皮纸手工剪贴簿质感',
    preset: '牛皮手工',
    description: '棕色牛皮纸纹理、图钉胶带装饰、手工做旧，适合旅行日记与手工记录',
    tags: ['牛皮纸', '手工', '怀旧'],
    mode: 'vintage',
    palette: {
      page: '#c4a67a',
      pageAlt: '#b8956a',
      text: '#2d1a0a',
      muted: '#6b5040',
      accent: '#8b4513',
      accentSoft: 'rgba(139,69,19,0.18)',
      border: 'rgba(139,69,19,0.16)',
      shadow: 'rgba(80,40,15,0.14)',
      glow: 'rgba(200,170,130,0.16)',
    },
    surface: {
      grainAlpha: 0.058,
      vignetteAlpha: 0.064,
      washStrength: 0.44,
      innerFrameAlpha: 0.12,
      innerFrameInset: 26,
      titleAccentMix: 0.84,
      footerLineAlpha: 0.22,
      footerTextAlpha: 0.90,
      previewShadow:
        '0 28px 56px rgba(80,40,15,0.14), 0 2px 20px rgba(200,170,130,0.30) inset',
    },
    components: {
      quoteFillAlpha: 0.058,
      quoteStrokeAlpha: 0.090,
      quoteBarAlpha: 0.76,
      quoteRadius: 14,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.72,
      highlightMarkerAlpha: 0.36,
      highlightDashAlpha: 0.84,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.84,
      bodyFontMode: 'kaiti',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: false, color1: '#b8956a', color2: '#c4a67a' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Swiss mode ────────────────────────────────────────────────────────────

  // ── 24。 business-brief (商务简报) ──────────────────────────────────────
  {
    id: 'business-brief',
    name: '商务简报',
    mood: '深蓝商务演示文稿专业',
    preset: '商务深蓝',
    description: '藏青标题栏、白底深灰文字、几何分隔线、数据条装饰，适合商务报告与演示',
    tags: ['商务', '简报', '专业'],
    mode: 'swiss',
    palette: {
      page: '#ffffff',
      pageAlt: '#f4f6fa',
      text: '#1a1a2e',
      muted: '#5e6a7a',
      accent: '#1e3a5f',
      accentSoft: 'rgba(30,58,95,0.14)',
      border: 'rgba(30,58,95,0.16)',
      shadow: 'rgba(20,40,60,0.08)',
      glow: 'rgba(30,58,95,0.05)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0.020,
      washStrength: 0,
      innerFrameAlpha: 0.18,
      innerFrameInset: 20,
      titleAccentMix: 0.66,
      footerLineAlpha: 0.24,
      footerTextAlpha: 0.92,
      previewShadow:
        '0 20px 44px rgba(20,40,60,0.08), 0 1px 8px rgba(0,0,0,0.03) inset',
    },
    components: {
      quoteFillAlpha: 0.022,
      quoteStrokeAlpha: 0.08,
      quoteBarAlpha: 0.80,
      quoteRadius: 4,
      quoteTreatment: 'callout',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.56,
      highlightMarkerAlpha: 0.22,
      highlightDashAlpha: 0.82,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.72,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'border',
    },
    category: 'professional',
    decor: { kind: 'cornerBracket', opacity: 0.24, scale: 1 },
    gradient: { enabled: false, color1: '#f4f6fa', color2: '#ffffff' },
  },

  // ── 25。 bytestyle (字节范) ─────────────────────────────────────────────
  {
    id: 'bytestyle',
    name: '字节范',
    mood: '字节跳动蓝白品牌科技',
    preset: '字节蓝白',
    description: '字节蓝白配色、几何色块、扁平设计、年轻活力，适合科技内容与飞书风格',
    tags: ['字节', '科技', '蓝白'],
    mode: 'swiss',
    palette: {
      page: '#f6f9ff',
      pageAlt: '#e8f0fe',
      text: '#1a1a2e',
      muted: '#5e6a8a',
      accent: '#3370ff',
      accentSoft: 'rgba(51,112,255,0.14)',
      border: 'rgba(51,112,255,0.16)',
      shadow: 'rgba(30,60,120,0.06)',
      glow: 'rgba(51,112,255,0.08)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0.018,
      washStrength: 0,
      innerFrameAlpha: 0.14,
      innerFrameInset: 20,
      titleAccentMix: 0.64,
      footerLineAlpha: 0.22,
      footerTextAlpha: 0.90,
      previewShadow:
        '0 16px 38px rgba(30,60,120,0.06), 0 1px 8px rgba(51,112,255,0.04) inset',
    },
    components: {
      quoteFillAlpha: 0.020,
      quoteStrokeAlpha: 0.072,
      quoteBarAlpha: 0.74,
      quoteRadius: 6,
      quoteTreatment: 'callout',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.56,
      highlightMarkerAlpha: 0.24,
      highlightDashAlpha: 0.80,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.76,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'border',
    },
    category: 'professional',
    decor: { kind: 'geometricPattern', opacity: 0.08, color: '#3370ff', scale: 1 },
    gradient: { enabled: false, color1: '#e8f0fe', color2: '#f6f9ff' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Obsidian mode ─────────────────────────────────────────────────────────

  // ── 26。 dark-mode (暗黑模式) ───────────────────────────────────────────
  {
    id: 'dark-mode',
    name: '暗黑模式',
    mood: 'App暗黑主题护眼现代',
    preset: '暗黑UI',
    description: '深灰底色、浅色文字、OLED友好、分层灰阶，适合夜间阅读与App暗色风格',
    tags: ['暗黑', '护眼', '现代'],
    mode: 'obsidian',
    palette: {
      page: '#16162a',
      pageAlt: '#20203c',
      text: '#e8e8f0',
      muted: '#888898',
      accent: '#6b7dff',
      accentSoft: 'rgba(107,125,255,0.16)',
      border: 'rgba(150,160,180,0.10)',
      shadow: 'rgba(6,6,24,0.50)',
      glow: 'rgba(107,125,255,0.08)',
    },
    surface: {
      grainAlpha: 0.05,
      vignetteAlpha: 0.08,
      washStrength: 0.20,
      innerFrameAlpha: 0.14,
      innerFrameInset: 24,
      titleAccentMix: 0.82,
      footerLineAlpha: 0.20,
      footerTextAlpha: 0.82,
      previewShadow:
        '0 28px 58px rgba(6,6,24,0.50), 0 2px 18px rgba(0,0,0,0.26) inset',
    },
    components: {
      quoteFillAlpha: 0.050,
      quoteStrokeAlpha: 0.092,
      quoteBarAlpha: 0.72,
      quoteRadius: 12,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.56,
      highlightMarkerAlpha: 0.36,
      highlightDashAlpha: 0.68,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.86,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: true, color1: '#16162a', color2: '#6b7dff' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Cyber mode ────────────────────────────────────────────────────────────

  // ── 27。 dark-tech (暗黑科技) ───────────────────────────────────────────
  {
    id: 'dark-tech',
    name: '暗黑科技',
    mood: '终端绿代码编辑器暗黑美学',
    preset: '终端代码',
    description: 'GitHub暗黑底、终端绿色高亮、等宽字体、扫描线，适合编程卡片与技术文档',
    tags: ['科技', '代码', '终端'],
    mode: 'cyber',
    palette: {
      page: '#0c1412',
      pageAlt: '#101c18',
      text: '#c8d0da',
      muted: '#6b7888',
      accent: '#00ff41',
      accentSoft: 'rgba(0,255,65,0.14)',
      border: 'rgba(0,255,65,0.16)',
      shadow: 'rgba(0,255,65,0.08)',
      glow: 'rgba(0,255,65,0.06)',
    },
    surface: {
      grainAlpha: 0.015,
      vignetteAlpha: 0.06,
      washStrength: 0.18,
      innerFrameAlpha: 0.12,
      innerFrameInset: 16,
      titleAccentMix: 0.86,
      footerLineAlpha: 0.22,
      footerTextAlpha: 0.84,
      previewShadow:
        '0 0 36px rgba(0,255,65,0.08), 0 0 72px rgba(0,200,50,0.04), 0 2px 14px rgba(0,0,0,0.40) inset',
    },
    components: {
      quoteFillAlpha: 0.040,
      quoteStrokeAlpha: 0.090,
      quoteBarAlpha: 0.76,
      quoteRadius: 2,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.52,
      highlightMarkerAlpha: 0.34,
      highlightDashAlpha: 0.70,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.76,
      bodyFontMode: 'dengxian',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'circuitTrace', opacity: 0.16, color: '#00ff41', scale: 1 },
    gradient: { enabled: true, color1: '#00ff41', color2: '#0c1412' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Glass mode ────────────────────────────────────────────────────────────

  // ── 28。 dreamy-gradient (梦幻渐变) ─────────────────────────────────────
  {
    id: 'dreamy-gradient',
    name: '梦幻渐变',
    mood: '多彩流体渐变梦幻迷离',
    preset: '梦幻虹彩',
    description: '紫罗兰到品红到天蓝流体渐变、星光粒子、磨砂玻璃，适合创意品牌与艺术内容',
    tags: ['梦幻', '渐变', '虹彩'],
    mode: 'glass',
    palette: {
      page: 'rgba(255,255,255,0.46)',
      pageAlt: 'rgba(248,238,255,0.36)',
      text: '#1a1530',
      muted: '#6e6888',
      accent: '#a855f7',
      accentSoft: 'rgba(168,85,247,0.18)',
      border: 'rgba(168,85,247,0.16)',
      shadow: 'rgba(168,85,247,0.10)',
      glow: 'rgba(190,160,255,0.18)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0.018,
      washStrength: 0.24,
      innerFrameAlpha: 0.06,
      innerFrameInset: 20,
      titleAccentMix: 0.72,
      footerLineAlpha: 0.14,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 14px 38px rgba(168,85,247,0.14), 0 2px 12px rgba(255,255,255,0.48) inset, 0 0 0 1px rgba(255,255,255,0.28) inset',
    },
    components: {
      quoteFillAlpha: 0.038,
      quoteStrokeAlpha: 0.074,
      quoteBarAlpha: 0.64,
      quoteRadius: 14,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.26,
      highlightDashAlpha: 0.66,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.80,
      bodyFontMode: 'yahei',
      bodyFontWeight: 350,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'auroraGlow', opacity: 0.14 },
    gradient: { enabled: true, color1: '#a855f7', color2: '#e8794c' },
  },

  // ── 29。 instagram (Instagram风格) ──────────────────────────────────────
  {
    id: 'instagram',
    name: 'Instagram风格',
    mood: 'IG社交平台潮流渐变',
    preset: 'IG潮流',
    description: '时尚渐变背景、白色粗体标题、社交互动元素、竖屏比例，适合社媒内容与品牌推广',
    tags: ['Instagram', '社交', '潮流'],
    mode: 'glass',
    palette: {
      page: 'rgba(255,255,255,0.48)',
      pageAlt: 'rgba(255,235,240,0.38)',
      text: '#1a1525',
      muted: '#6e6080',
      accent: '#e1306c',
      accentSoft: 'rgba(225,48,108,0.18)',
      border: 'rgba(225,48,108,0.16)',
      shadow: 'rgba(225,48,108,0.10)',
      glow: 'rgba(255,180,200,0.18)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0.014,
      washStrength: 0.22,
      innerFrameAlpha: 0.07,
      innerFrameInset: 22,
      titleAccentMix: 0.74,
      footerLineAlpha: 0.15,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 16px 38px rgba(225,48,108,0.14), 0 2px 12px rgba(255,255,255,0.48) inset, 0 0 0 1px rgba(255,255,255,0.28) inset',
    },
    components: {
      quoteFillAlpha: 0.038,
      quoteStrokeAlpha: 0.076,
      quoteBarAlpha: 0.68,
      quoteRadius: 16,
      quoteTreatment: 'callout',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.62,
      highlightMarkerAlpha: 0.30,
      highlightDashAlpha: 0.72,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.80,
      bodyFontMode: 'yahei',
      bodyFontWeight: 350,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'auroraGlow', opacity: 0.12 },
    gradient: { enabled: true, color1: '#e1306c', color2: '#f77737' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Brutal mode ───────────────────────────────────────────────────────────

  // ── 30。 pop-art (波普艺术) ─────────────────────────────────────────────
  {
    id: 'pop-art',
    name: '波普艺术',
    mood: '安迪沃霍尔大胆撞色漫画',
    preset: '波普撞色',
    description: '高饱和红黄蓝撞色、粗黑边框、网点纹理、漫画封面感，适合视觉冲击与创意表达',
    tags: ['波普', '撞色', '漫画'],
    mode: 'brutal',
    palette: {
      page: '#ffed00',
      pageAlt: '#ffed00',
      text: '#000000',
      muted: '#444444',
      accent: '#e6332a',
      accentSoft: 'rgba(230,51,42,0.24)',
      border: 'rgba(0,0,0,0.92)',
      shadow: 'rgba(0,0,0,0)',
      glow: 'rgba(0,0,0,0)',
    },
    surface: {
      grainAlpha: 0,
      vignetteAlpha: 0,
      washStrength: 0,
      innerFrameAlpha: 0.85,
      innerFrameInset: 10,
      titleAccentMix: 0,
      footerLineAlpha: 0.88,
      footerTextAlpha: 1.0,
      previewShadow:
        '5px 5px 0px rgba(0,0,0,0.88)',
    },
    components: {
      quoteFillAlpha: 0.04,
      quoteStrokeAlpha: 0.88,
      quoteBarAlpha: 0.96,
      quoteRadius: 0,
      quoteTreatment: 'code',
      highlightTreatment: 'swissRule',
      highlightUnderlineAlpha: 0.86,
      highlightMarkerAlpha: 0.64,
      highlightDashAlpha: 0.96,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.62,
      bodyFontMode: 'dengxian',
      bodyFontWeight: 500,
      subheadingStyle: 'accent',
      highlightStyle: 'border',
    },
    category: 'artistic',
    decor: { kind: 'none', opacity: 0 },
    gradient: { enabled: true, color1: '#ffed00', color2: '#e6332a' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Luxe mode ─────────────────────────────────────────────────────────────

  // ── 31。 art-deco (艺术装饰) ────────────────────────────────────────────
  {
    id: 'art-deco',
    name: '艺术装饰',
    mood: '爵士时代乌木金箔几何美学',
    preset: '装饰艺术',
    description: '乌木黑底、香槟金文、几何直角边框、抛光大理石质感，适合高端品牌宣言与珍藏级内容',
    tags: ['装饰艺术', '奢华', '几何'],
    mode: 'luxe',
    palette: {
      page: '#191714',         // 乌木黑 — 深邃抛光石材基底
      pageAlt: '#23201a',      // 深炭灰 — 微暖过渡
      text: '#e8dbb8',         // 香槟金 — 温暖光泽正文
      muted: '#9a8d6a',        // 哑光金 — 次级文本
      accent: '#d4af37',       // 金属金 — 纯正金色高光
      accentSoft: 'rgba(212,175,55,0.14)',
      border: 'rgba(212,175,55,0.20)',
      shadow: 'rgba(6,4,2,0.45)',
      glow: 'rgba(220,185,80,0.13)',
    },
    surface: {
      grainAlpha: 0.014,        // 极细颗粒 — 抛光大理石触感
      vignetteAlpha: 0.054,     // 更强暗角 — 聚光灯戏剧感
      washStrength: 0.28,       // 金色光晕更明显
      innerFrameAlpha: 0.20,    // 几何边框更醒目
      innerFrameInset: 30,      // 更宽的内框留白
      titleAccentMix: 0.96,     // 标题几乎纯金色
      footerLineAlpha: 0.28,    // 金色页脚分割线
      footerTextAlpha: 0.84,
      previewShadow:
        '0 30px 64px rgba(6,4,2,0.48), 0 2px 22px rgba(212,175,55,0.10) inset, 0 0 0 1px rgba(212,175,55,0.16) inset',
    },
    components: {
      quoteFillAlpha: 0.048,      // 金色微染引用底
      quoteStrokeAlpha: 0.096,    // 金色边框可见
      quoteBarAlpha: 0.88,        // 醒目金色强调条
      quoteRadius: 0,             // 直角 — Art Deco拒绝圆角
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.74,
      highlightMarkerAlpha: 0.30,
      highlightDashAlpha: 0.80,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.94,           // 更宽松的行距 — 奢华呼吸感
      bodyFontMode: 'fangsong',   // 仿宋 — 修长优雅的正文字
      bodyFontWeight: 350,
      subheadingStyle: 'accent',  // 金色小标题
      highlightStyle: 'underline',
    },
    category: 'professional',
    decor: { kind: 'fanBurst', opacity: 0.14, color: '#d4af37', scale: 1 },
    gradient: { enabled: false, color1: '#23201a', color2: '#191714' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── 32。 soft-minimal (极简柔光) ──────────────────────────────────────────
  //
  // 设计来源：UI.md「极简柔光卡片」提示词
  //   • macOS 窗口风格 · 大圆角矩形空白卡片
  //   • 外部：淡香芋紫 → 右下浅天蓝柔过渡
  //   • 内部：奶白基底 + 极浅淡粉紫 / 浅青蓝微渐变
  //   • 丝滑哑光柔焦 · 无杂纹理 · 悬浮投影
  //   • 低饱和马卡龙浅色系 · 柔和漫射光 · 温柔低对比度
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'soft-minimal',
    name: '极简柔光',
    mood: 'macOS窗口奶白马卡龙柔焦',
    preset: '极简柔光',
    description: 'macOS窗口风格、奶白基底配淡紫青蓝微渐变、丝滑哑光柔焦、悬浮投影，适合纯净写作与极简阅读',
    tags: ['极简', '柔光', '马卡龙'],
    mode: 'paper',
    palette: {
      // 内部底色：奶白基底 + 极浅淡粉紫／浅青蓝微渐变
      page: '#fdfaf8',
      // pageAlt：淡粉紫微染（渐变起点 — 左上淡香芋方向）
      pageAlt: '#f5eff4',
      text: '#2d2b2e',
      muted: '#a89faa',
      // 强调色：淡香芋紫 — 对应窗口装饰弧线 / 控制按钮
      accent: '#b8a2c8',
      accentSoft: 'rgba(184,162,200,0.14)',
      border: 'rgba(170,158,180,0.07)',
      // 投影色：低饱和紫灰 — 悬浮分层感
      shadow: 'rgba(155,142,168,0.07)',
      // 柔光光晕：淡紫 + 淡蓝混合漫射
      glow: 'rgba(200,188,215,0.24)',
    },
    surface: {
      // 无杂纹理（UI.md 明确要求）
      grainAlpha: 0,
      // 几乎零暗角 — 柔光不需要边缘压暗
      vignetteAlpha: 0.008,
      // 极淡柔光漫射
      washStrength: 0.12,
      // 微弱内框 — macOS 窗口感
      innerFrameAlpha: 0.04,
      // 大留白内缩 — 窗口内容区呼吸感
      innerFrameInset: 28,
      // 标题淡紫微染 — 不过分抢眼
      titleAccentMix: 0.4,
      footerLineAlpha: 0.08,
      footerTextAlpha: 0.76,
      // 微弱柔和投影 — 悬浮分层效果
      previewShadow:
        '0 8px 32px rgba(150,138,168,0.08), 0 2px 8px rgba(195,185,210,0.06), 0 0 0 1px rgba(255,255,255,0.5) inset',
    },
    components: {
      // 引用：极致克制，微底色 + 淡紫强调条
      quoteFillAlpha: 0.02,
      quoteStrokeAlpha: 0.035,
      quoteBarAlpha: 0.42,
      quoteRadius: 14,
      quoteTreatment: 'paper',
      // 高亮：柔和下划线
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.36,
      highlightMarkerAlpha: 0.12,
      highlightDashAlpha: 0.42,
    },
    editor: {
      bodySize: 28,
      lineHeight: 1.88,
      // 无衬线 — 现代极简
      bodyFontMode: 'yahei',
      bodyFontWeight: 300,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'light',
    // macOS 窗口风格：三色控制按钮 + 淡香芋紫弧线
    decor: { kind: 'macosWindow', opacity: 0.85, color: '#b8a2c8', scale: 1 },
    // 扁平柔和渐变：淡粉紫 → 浅青蓝（内部微渐变）
    gradient: {
      enabled: true,
      color1: '#f5eff4',
      color2: '#eff3f9',
      angle: 135,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── 33. canyon-sunset (日落峡谷) ──────────────────────────────────────────
  {
    id: 'canyon-sunset',
    name: '日落峡谷',
    mood: '美西南荒漠峡谷金色黄昏',
    preset: '峡谷日落',
    description: '赭石红底、沙漠金沙渐变、飞鸟剪影地平线，适合游记叙事与辽阔主题',
    tags: ['沙漠', '日落', '温暖'],
    mode: 'vintage',
    palette: {
      page: '#faf0e4',
      pageAlt: '#f2dcc8',
      text: '#3d2a1a',
      muted: '#8c6e5a',
      accent: '#c27a5c',
      accentSoft: 'rgba(194,122,92,0.18)',
      border: 'rgba(160,110,80,0.14)',
      shadow: 'rgba(140,90,60,0.10)',
      glow: 'rgba(240,200,160,0.30)',
    },
    surface: {
      grainAlpha: 0.044,
      vignetteAlpha: 0.048,
      washStrength: 0.36,
      innerFrameAlpha: 0.09,
      innerFrameInset: 26,
      titleAccentMix: 0.82,
      footerLineAlpha: 0.20,
      footerTextAlpha: 0.90,
      previewShadow:
        '0 26px 54px rgba(140,90,60,0.11), 0 2px 18px rgba(250,235,215,0.42) inset',
    },
    components: {
      quoteFillAlpha: 0.050,
      quoteStrokeAlpha: 0.078,
      quoteBarAlpha: 0.74,
      quoteRadius: 18,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.68,
      highlightMarkerAlpha: 0.34,
      highlightDashAlpha: 0.80,
    },
    editor: {
      bodySize: 30,
      lineHeight: 1.86,
      bodyFontMode: 'kaiti',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'desertSun', opacity: 0.88, color: '#c27a5c', scale: 1.05 },
    gradient: { enabled: true, color1: '#c27a5c', color2: '#f2d4a7', angle: 180 },
  },

  // ── 34. sakura-blizzard (樱吹雪) ─────────────────────────────────────────
  {
    id: 'sakura-blizzard',
    name: '樱吹雪',
    mood: '日式春樱散落花瓣柔美',
    preset: '樱吹雪',
    description: '淡粉花瓣底色、奶油暖白渐变、散落樱花点缀，适合春日随笔与温柔记录',
    tags: ['樱花', '春日', '柔美'],
    mode: 'paper',
    palette: {
      page: '#fefaf8',
      pageAlt: '#fce8ec',
      text: '#3d2a30',
      muted: '#9a7e84',
      accent: '#e8929e',
      accentSoft: 'rgba(232,146,158,0.18)',
      border: 'rgba(210,160,170,0.10)',
      shadow: 'rgba(180,140,150,0.08)',
      glow: 'rgba(250,215,220,0.28)',
    },
    surface: {
      grainAlpha: 0.016,
      vignetteAlpha: 0.024,
      washStrength: 0.20,
      innerFrameAlpha: 0.05,
      innerFrameInset: 28,
      titleAccentMix: 0.64,
      footerLineAlpha: 0.12,
      footerTextAlpha: 0.84,
      previewShadow:
        '0 20px 44px rgba(180,140,150,0.08), 0 2px 14px rgba(255,248,250,0.40) inset',
    },
    components: {
      quoteFillAlpha: 0.032,
      quoteStrokeAlpha: 0.054,
      quoteBarAlpha: 0.58,
      quoteRadius: 16,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.50,
      highlightMarkerAlpha: 0.20,
      highlightDashAlpha: 0.56,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.88,
      bodyFontMode: 'wenkai',
      bodyFontWeight: 300,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'light',
    decor: { kind: 'sakuraPetal', opacity: 0.85, color: '#e8929e', scale: 1.1 },
    gradient: { enabled: true, color1: '#fce8ec', color2: '#fffbf5', angle: 135 },
  },

  // ── 35. abyssal-coral (深海荧光) ─────────────────────────────────────────
  {
    id: 'abyssal-coral',
    name: '深海荧光',
    mood: '深海暗渊荧光珊瑚幽玄',
    preset: '深海珊瑚',
    description: '深渊海军蓝底、荧光珊瑚粉渐变、发光珊瑚枝装饰，适合神秘题材与科幻内容',
    tags: ['深海', '荧光', '幽玄'],
    mode: 'obsidian',
    palette: {
      page: '#0a1628',
      pageAlt: '#0d1a30',
      text: '#c8dae8',
      muted: '#6b8aa0',
      accent: '#ff6b6b',
      accentSoft: 'rgba(255,107,107,0.16)',
      border: 'rgba(100,160,200,0.10)',
      shadow: 'rgba(4,10,24,0.55)',
      glow: 'rgba(255,107,107,0.10)',
    },
    surface: {
      grainAlpha: 0.024,
      vignetteAlpha: 0.080,
      washStrength: 0.22,
      innerFrameAlpha: 0.12,
      innerFrameInset: 24,
      titleAccentMix: 0.88,
      footerLineAlpha: 0.22,
      footerTextAlpha: 0.84,
      previewShadow:
        '0 30px 62px rgba(4,10,24,0.55), 0 0 40px rgba(255,107,107,0.06), 0 2px 20px rgba(0,0,0,0.30) inset',
    },
    components: {
      quoteFillAlpha: 0.048,
      quoteStrokeAlpha: 0.090,
      quoteBarAlpha: 0.78,
      quoteRadius: 12,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.58,
      highlightMarkerAlpha: 0.38,
      highlightDashAlpha: 0.72,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.86,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'coralBranch', opacity: 0.85, color: '#ff6b6b', scale: 1.08 },
    gradient: { enabled: true, color1: '#0a1628', color2: '#ff6b6b', angle: 160 },
  },

  // ── 36. amethyst-geode (紫晶洞) ───────────────────────────────────────────
  {
    id: 'amethyst-geode',
    name: '紫晶洞',
    mood: '紫水晶晶洞神秘深邃',
    preset: '紫晶洞窟',
    description: '深紫黑底、紫水晶渐变、晶体棱面切角装饰，适合神秘学与奇幻文学',
    tags: ['水晶', '紫色', '奇幻'],
    mode: 'obsidian',
    palette: {
      page: '#1a0a2e',
      pageAlt: '#1f103a',
      text: '#d8cfe8',
      muted: '#8a7ea8',
      accent: '#9b6dff',
      accentSoft: 'rgba(155,109,255,0.16)',
      border: 'rgba(155,109,255,0.14)',
      shadow: 'rgba(12,4,24,0.55)',
      glow: 'rgba(155,109,255,0.12)',
    },
    surface: {
      grainAlpha: 0.030,
      vignetteAlpha: 0.076,
      washStrength: 0.24,
      innerFrameAlpha: 0.13,
      innerFrameInset: 26,
      titleAccentMix: 0.90,
      footerLineAlpha: 0.22,
      footerTextAlpha: 0.84,
      previewShadow:
        '0 28px 60px rgba(12,4,24,0.55), 0 0 50px rgba(155,109,255,0.08), 0 2px 18px rgba(0,0,0,0.28) inset',
    },
    components: {
      quoteFillAlpha: 0.044,
      quoteStrokeAlpha: 0.086,
      quoteBarAlpha: 0.76,
      quoteRadius: 8,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.60,
      highlightMarkerAlpha: 0.36,
      highlightDashAlpha: 0.74,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.88,
      bodyFontMode: 'yahei',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'dark',
    decor: { kind: 'crystalFacet', opacity: 0.88, color: '#9b6dff', scale: 1.08 },
    gradient: { enabled: true, color1: '#1a0a2e', color2: '#9b6dff', angle: 45 },
  },

  // ── 37. charcoal-sketch (炭笔素描) ───────────────────────────────────────
  {
    id: 'charcoal-sketch',
    name: '炭笔素描',
    mood: '艺术家素描本炭笔排线',
    preset: '炭笔手稿',
    description: '暖纸白底、炭灰色渐变、交叉排线角饰，适合草稿笔记与创作构思',
    tags: ['素描', '炭笔', '手稿'],
    mode: 'paper',
    palette: {
      page: '#f5f0e8',
      pageAlt: '#e8e2d8',
      text: '#2d2a26',
      muted: '#7a7670',
      accent: '#5a5550',
      accentSoft: 'rgba(90,85,80,0.12)',
      border: 'rgba(90,85,80,0.12)',
      shadow: 'rgba(60,55,50,0.08)',
      glow: 'rgba(180,175,165,0.16)',
    },
    surface: {
      grainAlpha: 0.048,
      vignetteAlpha: 0.044,
      washStrength: 0.18,
      innerFrameAlpha: 0.08,
      innerFrameInset: 24,
      titleAccentMix: 0.68,
      footerLineAlpha: 0.16,
      footerTextAlpha: 0.88,
      previewShadow:
        '0 22px 46px rgba(60,55,50,0.08), 0 2px 14px rgba(245,240,232,0.38) inset',
    },
    components: {
      quoteFillAlpha: 0.036,
      quoteStrokeAlpha: 0.064,
      quoteBarAlpha: 0.62,
      quoteRadius: 8,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.54,
      highlightMarkerAlpha: 0.22,
      highlightDashAlpha: 0.64,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.82,
      bodyFontMode: 'fangsong',
      bodyFontWeight: 400,
      subheadingStyle: 'large',
      highlightStyle: 'underline',
    },
    category: 'professional',
    decor: { kind: 'sketchHatch', opacity: 0.78, color: '#5a5550', scale: 1.05 },
    gradient: { enabled: true, color1: '#f5f0e8', color2: '#d5cec5', angle: 135 },
  },

  // ── 38. matcha-zen (抹茶禅意) ───────────────────────────────────────────
  {
    id: 'matcha-zen',
    name: '抹茶禅意',
    mood: '日本茶道抹茶泡沫禅静',
    preset: '抹茶禅',
    description: '陶胚奶油底、抹茶绿渐变、茶筅涟漪圈饰，适合茶道笔记与禅意内容',
    tags: ['抹茶', '禅意', '和风'],
    mode: 'sage',
    palette: {
      page: '#faf7f0',
      pageAlt: '#eef0e0',
      text: '#2d3320',
      muted: '#7a8065',
      accent: '#8ba87a',
      accentSoft: 'rgba(139,168,122,0.16)',
      border: 'rgba(120,150,100,0.10)',
      shadow: 'rgba(90,110,70,0.07)',
      glow: 'rgba(200,225,185,0.22)',
    },
    surface: {
      grainAlpha: 0.028,
      vignetteAlpha: 0.030,
      washStrength: 0.22,
      innerFrameAlpha: 0.06,
      innerFrameInset: 28,
      titleAccentMix: 0.72,
      footerLineAlpha: 0.14,
      footerTextAlpha: 0.86,
      previewShadow:
        '0 20px 44px rgba(90,110,70,0.07), 0 2px 14px rgba(250,247,240,0.40) inset',
    },
    components: {
      quoteFillAlpha: 0.034,
      quoteStrokeAlpha: 0.058,
      quoteBarAlpha: 0.60,
      quoteRadius: 14,
      quoteTreatment: 'paper',
      highlightTreatment: 'softUnderline',
      highlightUnderlineAlpha: 0.52,
      highlightMarkerAlpha: 0.20,
      highlightDashAlpha: 0.60,
    },
    editor: {
      bodySize: 29,
      lineHeight: 1.88,
      bodyFontMode: 'wenkai',
      bodyFontWeight: 400,
      subheadingStyle: 'accent',
      highlightStyle: 'underline',
    },
    category: 'artistic',
    decor: { kind: 'matchaRing', opacity: 0.84, color: '#8ba87a', scale: 1.06 },
    gradient: { enabled: true, color1: '#faf7f0', color2: '#8ba87a', angle: 135 },
  },
]

/** 未指定时使用的默认主题 ID。 */
export const DEFAULT_THEME_ID = 'moss-paper'

/** 按 ID 查找主题。回退到第一个主题。 */
export function getTheme(id: string): ThemeDefinition {
  return THEMES.find((t) => t.id === id) ?? THEMES[0]
}